CREATE TABLE "emp" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" varchar NOT NULL,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "cursos" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "emp_id" bigint REFERENCES "emp" ("id"),
    "nome" varchar NOT NULL,
    "descricao" text,
    "ativo" boolean,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "turmas" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "curso_id" bigint REFERENCES "cursos" ("id"),
    "nome" varchar NOT NULL,
    "data_inicio" date,
    "data_fim" date,
    "status" varchar,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "aulas" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "turma_id" bigint REFERENCES "turmas" ("id"),
    "data" timestamp,
    "tema" varchar,
    "observacoes" text,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "trajetoria" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" varchar NOT NULL,
    "descricao" text,
    "ativa" boolean,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "grupos_trajetoria" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trajetoria_id" bigint REFERENCES "trajetoria" ("id"),
    "nome" varchar NOT NULL,
    "ordem" int,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "passos" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "curso_id" bigint REFERENCES "cursos" ("id"),
    "nome" varchar NOT NULL,
    "descricao" text,
    "ordem" int,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "grupo_trajetoria_passos" (
    "grupo_id" bigint REFERENCES "grupos_trajetoria" ("id"),
    "passo_id" bigint REFERENCES "passos" ("id"),
    PRIMARY KEY ("grupo_id", "passo_id")
);

CREATE TABLE "trajetoria_passos" (
    "trajetoria_id" bigint REFERENCES "trajetoria" ("id"),
    "passo_id" bigint REFERENCES "passos" ("id"),
    PRIMARY KEY ("trajetoria_id", "passo_id")
);

CREATE TABLE "grupos" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" varchar NOT NULL,
    "grupo_pai" bigint REFERENCES "grupos" ("id"),
    "tipo" varchar,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "celulas" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "grupo_id" bigint REFERENCES "grupos" ("id"),
    "nome" varchar NOT NULL,
    "dia_semana" varchar,
    "horario" time,
    "local" text,
    "ativa" boolean NOT NULL,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "metas" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" varchar NOT NULL,
    "descricao" varchar,
    "grupo_id" bigint REFERENCES "grupos" ("id"),
    "periodo_inicio" date,
    "periodo_fim" date,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "celula_metas" (
    "celula_id" bigint REFERENCES "celulas" ("id"),
    "meta_id" bigint REFERENCES "metas" ("id"),
    "valor_esperado" bigint,
    "valor_alcancado" bigint,
    "observacoes" text,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false,
    PRIMARY KEY ("celula_id", "meta_id")
);

CREATE TABLE "grupo_metas" (
    "grupo_id" bigint REFERENCES "grupos" ("id"),
    "meta_id" bigint REFERENCES "metas" ("id"),
    "valor_esperado" bigint,
    "valor_alcancado" bigint,
    "observacoes" text,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false,
  PRIMARY KEY ("grupo_id", "meta_id")
);

CREATE TABLE "encontros" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "celula_id" bigint REFERENCES "celulas" ("id"),
    "data" date NOT NULL,
    "horario" time NOT NULL,
    "local" text NOT NULL,
    "tema" varchar NOT NULL,
    "observacoes" text,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "membros" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
    "data_nascimento" date,
    "ativo" boolean NOT NULL,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "membros_celula" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "celula_id" bigint REFERENCES "celulas" ("id"),
    "membro_id" bigint REFERENCES "membros" ("id"),
    "papel_celula" varchar,
    "data_entrada" date,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "inscricoes" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "turma_id" bigint REFERENCES "turmas" ("id"),
    "participante_id" bigint REFERENCES "membros" ("id"),
    "data_inscricao" timestamp,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "frequencias_curso" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "aula_id" bigint REFERENCES "aulas" ("id"),
    "inscricao_id" bigint REFERENCES "inscricoes" ("id"),
    "presente" boolean NOT NULL,
    "justificado" boolean NOT NULL,
    "justificativa" text,
    "observacoes" text,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "membros_passos" (
  "membro_id" bigint REFERENCES "membros" ("id"),
  "passo_id" bigint REFERENCES "passos" ("id"),
  "status" varchar,
  "data_inicio" date,
  "data_conclusao" date,
  PRIMARY KEY ("membro_id", "passo_id")
);

CREATE TABLE "frequencias_celula" (
    "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "encontro_id" bigint REFERENCES "encontros" ("id"),
    "membro_id" bigint REFERENCES "membros" ("id"),
    "presente" boolean,
    "justificado" boolean,
    "justificativa" text,
    "criado_em" timestamp NOT NULL,
    "criado_por" varchar(255) NOT NULL,
    "atualizado_em" timestamp,
    "atualizado_por" varchar(255),
    "deletado" boolean not null default false
);

CREATE TABLE "acompanhamentos_pastorais" (
  "id"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data" timestamp NOT NULL,
  "observacoes" text,
  "tipo" varchar
);

CREATE TABLE "acompanhamento_pastoral_membros" (
  "acompanhamento_id" bigint REFERENCES "acompanhamentos_pastorais" ("id"),
  "membro_id" bigint REFERENCES "membros" ("id"),
  PRIMARY KEY ("acompanhamento_id", "membro_id")
);