-- Immutable audit log for manual trajectory / EMP course advances
-- Run after: alter_membros_passos_inscricoes_avancos.sql

CREATE TABLE IF NOT EXISTS public.historico_avancos_manuais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membro_id BIGINT NOT NULL REFERENCES public.membros(id),
  tipo VARCHAR NOT NULL,
  referencia_id BIGINT NOT NULL,
  registrado_em TIMESTAMP NOT NULL DEFAULT NOW(),
  registrado_por VARCHAR(255) NOT NULL,
  observacao TEXT,
  deletado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_historico_avancos_membro_id
  ON public.historico_avancos_manuais(membro_id)
  WHERE deletado = FALSE;

COMMENT ON TABLE public.historico_avancos_manuais IS 'Auditoria de avanços manuais em trajetória (PASSO) ou cursos EMP (INSCRICAO_EMP).';
COMMENT ON COLUMN public.historico_avancos_manuais.tipo IS 'PASSO ou INSCRICAO_EMP';
COMMENT ON COLUMN public.historico_avancos_manuais.referencia_id IS 'passo_id ou inscricao_id conforme tipo';

-- RLS for historico (requires helper functions from rls_edicao_membro_avancos.sql)
-- If you run only this file without migration 3, apply policies after creating the functions.
