CREATE TABLE IF NOT EXISTS public.multiplicacao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  celula_origem_id bigint NOT NULL,
  celula_destino_id bigint,
  data_multiplicacao date,
  status_multiplicacao varchar,
  observacoes text,
  deletado boolean NOT NULL DEFAULT false,
  criado_em timestamp NOT NULL,
  criado_por varchar NOT NULL,
  atualizado_em timestamp,
  atualizado_por varchar,
  lider_membro_id bigint REFERENCES public.membros(id) ON DELETE SET NULL,
  nome_celula_destino text
);

CREATE TABLE IF NOT EXISTS public.multiplicacao_membros (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membro_id bigint NOT NULL REFERENCES public.membros(id),
  multiplicacao_id bigint REFERENCES public.multiplicacao(id),
  papel_celula varchar,
  observacoes text,
  deletado boolean NOT NULL DEFAULT false,
  criado_em timestamp NOT NULL,
  criado_por varchar NOT NULL,
  atualizado_em timestamp,
  atualizado_por varchar,
  lider_nova_celula boolean NOT NULL DEFAULT false
);

ALTER TABLE public.multiplicacao
  ADD COLUMN IF NOT EXISTS lider_membro_id bigint REFERENCES public.membros(id) ON DELETE SET NULL;

ALTER TABLE public.multiplicacao
  ADD COLUMN IF NOT EXISTS nome_celula_destino text;

UPDATE public.multiplicacao m
SET nome_celula_destino = c.nome
FROM public.celulas c
WHERE m.celula_destino_id = c.id
  AND m.nome_celula_destino IS NULL;

UPDATE public.multiplicacao
SET status_multiplicacao = CASE status_multiplicacao
  WHEN 'PLANEJADA' THEN 'Em planejamento'
  WHEN 'EM_ANDAMENTO' THEN 'Em análise'
  WHEN 'CONCLUIDA' THEN 'Finalizada'
  WHEN 'CANCELADA' THEN 'Em planejamento'
  ELSE status_multiplicacao
END
WHERE status_multiplicacao IN ('PLANEJADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA');

ALTER TABLE public.multiplicacao_membros
  ADD COLUMN IF NOT EXISTS lider_nova_celula boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_multiplicacao_lider_membro_id
  ON public.multiplicacao(lider_membro_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_multiplicacao_membros_um_lider
  ON public.multiplicacao_membros(multiplicacao_id)
  WHERE lider_nova_celula IS TRUE AND deletado = false;
