-- RLS: leader can UPDATE membros; leader/auxiliar can register advances
-- Run after: alter_membros_passos_inscricoes_avancos.sql
-- historico_avancos_manuais is created below if missing (migration 2 optional)

CREATE OR REPLACE FUNCTION public.get_membro_id_do_usuario()
RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id
  FROM public.membros
  WHERE user_id = auth.uid()
    AND deletado = FALSE
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.usuario_papel_na_celula(p_celula_id BIGINT)
RETURNS VARCHAR
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT mc.papel_celula
  FROM public.membros_celula mc
  WHERE mc.membro_id = public.get_membro_id_do_usuario()
    AND mc.celula_id = p_celula_id
    AND mc.deletado = FALSE
    AND mc.data_saida IS NULL
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.membros_compartilham_celula_ativa(p_membro_alvo_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.membros_celula usuario_mc
    INNER JOIN public.membros_celula alvo_mc
      ON alvo_mc.celula_id = usuario_mc.celula_id
    WHERE usuario_mc.membro_id = public.get_membro_id_do_usuario()
      AND alvo_mc.membro_id = p_membro_alvo_id
      AND usuario_mc.deletado = FALSE
      AND usuario_mc.data_saida IS NULL
      AND alvo_mc.deletado = FALSE
      AND alvo_mc.data_saida IS NULL
      AND usuario_mc.papel_celula IN ('LIDER_CELULA', 'AUXILIAR_CELULA')
  );
$$;

CREATE OR REPLACE FUNCTION public.usuario_e_lider_na_celula_do_membro(p_membro_alvo_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.membros_celula usuario_mc
    INNER JOIN public.membros_celula alvo_mc
      ON alvo_mc.celula_id = usuario_mc.celula_id
    WHERE usuario_mc.membro_id = public.get_membro_id_do_usuario()
      AND alvo_mc.membro_id = p_membro_alvo_id
      AND usuario_mc.deletado = FALSE
      AND usuario_mc.data_saida IS NULL
      AND alvo_mc.deletado = FALSE
      AND alvo_mc.data_saida IS NULL
      AND usuario_mc.papel_celula = 'LIDER_CELULA'
  );
$$;

-- membros
ALTER TABLE public.membros ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS membros_select_authenticated ON public.membros;
CREATE POLICY membros_select_authenticated
  ON public.membros
  FOR SELECT
  TO authenticated
  USING (deletado = FALSE);

DROP POLICY IF EXISTS membros_update_por_lider_celula ON public.membros;
CREATE POLICY membros_update_por_lider_celula
  ON public.membros
  FOR UPDATE
  USING (public.usuario_e_lider_na_celula_do_membro(id))
  WITH CHECK (public.usuario_e_lider_na_celula_do_membro(id));

-- membros_passos
ALTER TABLE public.membros_passos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS membros_passos_select_authenticated ON public.membros_passos;
CREATE POLICY membros_passos_select_authenticated
  ON public.membros_passos
  FOR SELECT
  TO authenticated
  USING (deletado = FALSE);

DROP POLICY IF EXISTS membros_passos_insert_por_lideranca ON public.membros_passos;
CREATE POLICY membros_passos_insert_por_lideranca
  ON public.membros_passos
  FOR INSERT
  WITH CHECK (public.membros_compartilham_celula_ativa(membro_id));

DROP POLICY IF EXISTS membros_passos_update_por_lideranca ON public.membros_passos;
CREATE POLICY membros_passos_update_por_lideranca
  ON public.membros_passos
  FOR UPDATE
  USING (public.membros_compartilham_celula_ativa(membro_id))
  WITH CHECK (public.membros_compartilham_celula_ativa(membro_id));

-- inscricoes
ALTER TABLE public.inscricoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inscricoes_select_authenticated ON public.inscricoes;
CREATE POLICY inscricoes_select_authenticated
  ON public.inscricoes
  FOR SELECT
  TO authenticated
  USING (deletado = FALSE);

DROP POLICY IF EXISTS inscricoes_update_conclusao_por_lideranca ON public.inscricoes;
CREATE POLICY inscricoes_update_conclusao_por_lideranca
  ON public.inscricoes
  FOR UPDATE
  USING (
  public.membros_compartilham_celula_ativa(participante_id)
  )
  WITH CHECK (
  public.membros_compartilham_celula_ativa(participante_id)
  );

-- historico_avancos_manuais (create if migration 2 was not applied)
CREATE TABLE IF NOT EXISTS public.historico_avancos_manuais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membro_id BIGINT NOT NULL REFERENCES public.membros(id),
  tipo VARCHAR NOT NULL,
  referencia_id BIGINT NOT NULL,
  registrado_em TIMESTAMP NOT NULL DEFAULT NOW(),
  registrado_por VARCHAR(255) NOT NULL,
  observacao TEXT,
  deletado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_historico_avancos_membro_id
  ON public.historico_avancos_manuais(membro_id)
  WHERE deletado = FALSE;

ALTER TABLE public.historico_avancos_manuais ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS historico_avancos_select_authenticated ON public.historico_avancos_manuais;
CREATE POLICY historico_avancos_select_authenticated
  ON public.historico_avancos_manuais
  FOR SELECT
  TO authenticated
  USING (deletado = FALSE);

DROP POLICY IF EXISTS historico_avancos_insert_por_lideranca ON public.historico_avancos_manuais;
CREATE POLICY historico_avancos_insert_por_lideranca
  ON public.historico_avancos_manuais
  FOR INSERT
  WITH CHECK (public.membros_compartilham_celula_ativa(membro_id));
